import '@testing-library/jest-dom'
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'

// Initialize i18next synchronously for tests — no HTTP backend needed.
// Tests assert against real English strings, not translation keys.
//
// MAINTENANCE: Keep these inline resources in sync with public/locales/en/*.json.
// If you add a key to a JSON file but omit it here, tests will display raw
// translation keys (e.g. "nav.settings") instead of real strings.
i18n.use(initReactI18next).init({
  lng: 'en',
  fallbackLng: 'en',
  resources: {
    en: {
      nav: {
        wordmarkPrefix: 'h',
        wordmarkDot: '.',
        wordmarkSuffix: 'care',
        agencySubtitle: 'Agency Management',
        schedule: 'Schedule',
        dashboard: 'Dashboard',
        clients: 'Clients',
        caregivers: 'Caregivers',
        payers: 'Payers',
        evvStatus: 'EVV Status',
        settings: 'Settings',
        settingsComingSoon: 'Settings — coming soon',
        sectionOperations: 'Operations',
        sectionPeople: 'People',
        sectionAdmin: 'Admin',
      },
      common: {
        back: '← Back',
        unassigned: 'Unassigned',
        noDash: '—',
        yes: 'Yes',
        no: 'No',
        cancel: 'Cancel',
        searchByName: 'Search by name…',
        noExpiry: 'No expiry',
      },
      schedule: {
        pageTitle: 'Schedule',
        backLabel: '← Schedule',
        newShift: '+ New Shift',
        broadcastOpen: 'Broadcast Open',
        broadcastOpenAlert: 'Broadcast Open: confirms then broadcasts all unassigned shifts',
        prevWeek: '←',
        nextWeek: '→',
        alertStripToday: 'Today:',
        alertRedEvv: 'RED EVV',
        alertYellowEvv: 'YELLOW EVV',
        alertUncovered: 'Uncovered',
        alertLateClockIn: 'Late clock-in',
        settingsComingSoon: 'Settings — coming soon',
        newShiftAt: 'New shift at {{hour}}:00',
      },
      shiftDetail: {
        notFound: 'Shift not found.',
        sectionVisitDetails: 'Visit Details',
        sectionEvvRecord: 'EVV Record',
        sectionAiMatch: 'AI Match — Top Candidates',
        fieldClient: 'Client',
        fieldCaregiver: 'Caregiver',
        fieldService: 'Service',
        fieldStatus: 'Status',
        fieldClockIn: 'Clock-in',
        fieldClockOut: 'Clock-out',
        fieldMethod: 'Method',
        fieldOffline: 'Offline',
        unknownClient: 'Unknown Client',
        staticService: 'PCS',
        visitNotStarted: ' — Visit not yet started',
        evvCompliant: 'Compliant',
        evvAttention: 'Attention Required',
        evvNonCompliant: 'Non-Compliant',
        evvNotStarted: 'Not Started',
        evvExempt: 'Exempt',
        evvPortalSubmit: 'Portal Submit',
        assignCaregiver: 'Assign Caregiver',
        addManualClockIn: 'Add Manual Clock-in',
        editShift: 'Edit Shift',
        markAsMissed: 'Mark as Missed',
        viewCareNotes: 'View Care Notes',
        candidate1Name: 'Maria Garcia',
        candidate1Reason: '0.8 mi · 12 prior visits · no OT risk',
        candidate2Name: 'Sarah Davis',
        candidate2Reason: '1.4 mi · 5 prior visits · no OT risk',
        assign: 'Assign →',
      },
      newShift: {
        panelTitle: 'New Shift',
        labelClient: 'Client',
        labelServiceType: 'Service Type',
        labelDate: 'Date',
        labelStartTime: 'Start Time',
        labelEndTime: 'End Time',
        labelCaregiver: 'Caregiver (optional)',
        selectClient: 'Select client…',
        selectServiceType: 'Select service type…',
        serviceTypePcs: 'PCS — Personal Care Services',
        caregiverUnassigned: 'Leave unassigned (broadcast after)',
        caregiverPhaseNote: 'Phase 4 will populate this list from the API.',
        validationRequired: 'This field is required',
        validationClientRequired: 'Client is required',
        validationServiceTypeRequired: 'Service type is required',
        validationDateRequired: 'Date is required',
        saveShift: 'Save Shift',
        mockAlert: 'Mock: shift for client {{clientId}} on {{date}} created.\n\nPhase 4 will wire this to POST /shifts.',
      },
      dashboard: {
        pageTitle: 'Dashboard',
        backLabel: '← Dashboard',
        tileRedEvv: 'RED EVV',
        tileRedEvvSub: 'Missing elements',
        tileYellowEvv: 'YELLOW EVV',
        tileYellowEvvSub: 'Attention needed',
        tileUncovered: 'UNCOVERED',
        tileUncoveredSub: 'No caregiver',
        tileOnTrack: 'ON TRACK',
        tileOnTrackSub: 'Compliant',
        noVisits: 'No visits today.',
        noAlerts: 'No active alerts.',
        alertsHeader: 'Alerts',
        due: 'Due {{date}}',
      },
      clients: {
        pageTitle: 'Clients',
        backLabel: '← Clients',
        addClient: '+ Add Client',
        addClientAlert: 'Add Client — Phase 6 will wire this form.',
        notFound: 'Client not found.',
        noResults: 'No clients found.',
        colClient: 'Client',
        colMedicaidId: 'Medicaid ID',
        colState: 'State',
        colStatus: 'Status',
        tabOverview: 'Overview',
        tabCarePlan: 'Care Plan',
        tabAuthorizations: 'Authorizations',
        tabDocuments: 'Documents',
        tabFamilyPortal: 'Family Portal',
        fieldPhone: 'Phone',
        fieldAddress: 'Address',
        fieldServiceState: 'Service State',
        fieldStatus: 'Status',
        fieldPreferredLanguage: 'Preferred Language',
        fieldNoPetCaregiver: 'No Pet Caregiver',
        noAuthorizations: 'No authorizations.',
        carePlanPhaseNote: 'Care plan — Phase 6 wires to real API.',
        documentsPhaseNote: 'Documents — Phase 6 wires to real API.',
        familyPortalPhaseNote: 'Family portal — Phase 6 wires to real API.',
        authHeader: 'Auth #{{authNumber}}',
        authUnitsUsed: '{{used}}/{{authorized}} {{unitType}}s used',
      },
      caregivers: {
        pageTitle: 'Caregivers',
        backLabel: '← Caregivers',
        addCaregiver: '+ Add Caregiver',
        addCaregiverAlert: 'Add Caregiver — Phase 7 will wire this form.',
        notFound: 'Caregiver not found.',
        noResults: 'No caregivers found.',
        colCaregiver: 'Caregiver',
        colEmail: 'Email',
        colPhone: 'Phone',
        colStatus: 'Status',
        colHireDate: 'Hire Date',
        tabOverview: 'Overview',
        tabCredentials: 'Credentials',
        tabBackgroundChecks: 'Background Checks',
        tabAvailability: 'Availability',
        tabShiftHistory: 'Shift History',
        fieldPhone: 'Phone',
        fieldAddress: 'Address',
        fieldHireDate: 'Hire Date',
        fieldStatus: 'Status',
        fieldHasPet: 'Has Pet',
        noCredentials: 'No credentials on file.',
        credExpires: 'Expires:',
        credExpiringSoon: 'Expiring soon',
        credVerified: 'Verified',
        credUnverified: 'Unverified',
        backgroundPhaseNote: 'Background checks — Phase 7 wires to real API.',
        availabilityPhaseNote: 'Availability — Phase 7 wires to real API.',
        shiftHistoryPhaseNote: 'Shift history — Phase 7 wires to real API.',
      },
      payers: {
        pageTitle: 'Payers',
        addPayer: '+ Add Payer',
        addPayerAlert: 'Phase 8 will wire this to the API.',
        colPayerName: 'Payer Name',
        colType: 'Type',
        colState: 'State',
        colEvvAggregator: 'EVV Aggregator',
        typeMedicaid: 'Medicaid',
        typePrivatePay: 'Private Pay',
        typeLtcInsurance: 'LTC Insurance',
        typeVa: 'VA',
        typeMedicare: 'Medicare',
      },
      evvStatus: {
        pageTitle: 'EVV Status',
        backLabel: '← EVV Status',
        subtitle: 'Last 30 days — computed live from Core API',
        colClient: 'Client',
        colCaregiver: 'Caregiver',
        colService: 'Service',
        colDate: 'Date',
        colClockIn: 'Clock-in',
        colClockOut: 'Clock-out',
        colStatus: 'Status',
      },
    },
  },
  interpolation: { escapeValue: false },
})
