spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
  flyway:
    locations: classpath:db/migration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

hcare:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
